spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CortesV/BP_Configuration
          username: CortesV
          password: 26061996sis
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: when_authorized
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, ODD, EVEN, UP